import { makeStyles } from '@material-ui/core/styles'

export const useStyles = makeStyles({
  root: {
    marginTop: '140px',
    marginLeft: '120px',
    padding: '28px',
    backgroundColor: 'hsl(0, 0%, 98%)',
  },
  totalStat: {
    display: 'grid',
    gridGap: '24px',
    gridTemplateColumns: 'repeat(4,1fr)',
    padding: 0,
  },
  cardTable: {
    paddingTop: '32px',
    paddingBottom: '24px',
    display: 'flex',
    tableLayout: 'auto',
  },
  chart: {
    display: 'flex',
    width: '100%',
    marginTop: '2%',
    padding: '24px 16px',
    borderRadius: '8px',
    background: '#fff',
    boxShadow: '0 1px 15px 0 hsl(0deg 0% 48% / 5%)',
  },
  chartleft: {
    width: '48%',
  },
  chartright: {
    width: '48%',
    marginLeft: '4%',
  },
  studentsection: {
    display: 'block',
    padding: '28px',
    webkitTextSizeAdjust: '100%',
  },
  studentstat: {
    marginTop: 0,
    fontFamily: 'Arial',
    display: 'grid',
    gridGap: '24px',
    gridTemplateColumns: 'repeat(1,275px auto 30%)',
    padding: 0,
    margin: '64px 0',
  },
  card: {
    borderRadius: '8px',
    backgroundColor: '#fff',
    boxShadow: '0 1px 15px 0 hsl(0deg 0% 48% / 5%)',
    boxSizing: 'border-box',
  },
  cardStudent: {
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  cardImg: {
    width: '100%',
    height: '189px',
    objectFit: 'cover',
    borderStyle: 'none',
  },
  cardBody: {
    padding: '16px',
    outline: 'none',
    fontFamily: 'Arial',
  },
  cardTitle: {
    color: '#485465',
    fontSize: '18px',
    fontWeight: 600,
    display: 'block',
    marginBottom: '8px',
    paddingLeft: '14px',
    paddingTop: '14px',
  },
  cardDetail: {
    color: '#a7a7a7',
    fontFamily: 'Lato,Arial,Helvetica,sans-serif',
    fontSize: '14px',
    paddingLeft: '14px',
    display: 'block',
    marginBottom: '8px',
  },
  cardCredit: {
    fontSize: '18px',
    fontWeight: 'bolder',
    boxSizing: 'border-box',
    color: '#a7a7a7',
    paddingLeft: '14px',
  },
  cardLink: {
    backgroundColor: 'rgba(0,0,0,.1)',
    textAlign: 'center',
    textDecoration: 'none',
    transition: '0.3s',
    padding: '8px 0',
    marginTop: 'auto',
    display: 'block',
    color: '#4183c4',
  },
  studentstatBox: {
    marginTop: 0,
    display: 'grid',
    gridGap: '24px',
    gridTemplateColumns: 'repeat(2,1fr)',
    padding: 0,
    boxSizing: 'border-box',
  },
  activity: {
    borderRadius: '4px',
    overflow: 'hidden',
    flex: 1,
    backgroundColor: '#fff',
    boxSizing: 'border-box',
    margin: 0,
    padding: 0,
  },
  activityTitleWrap: {
    padding: '24px 16px 0',
    backgroundColor: '#fff',
    outline: 'none',
  },
  activitytitle: {
    fontSize: '1.07142857rem',
    color: '#485465',
    marginTop: 0,
    marginBottom: 0,
  },
  numbers: {
    color: '#bf8dee',
    fontSize: '30px',
    fontWeight: 'bolder',
    paddingLeft: '14px',
  },
  paragraph: {
    fontSize: '12px',
    lineHeight: '1.4285em',
    color: '#a7a7a7',
    fontFamily: 'Arial',
    paddingLeft: '14px',
  },
  link: {
    fontStyle: 'none',
    fontWeight: 'normal',
    textDecoration: 'none',
    color: 'rgb(40, 109, 205)',
  },
})
